### PR TITLE
Switched from crypto to pointycastle and added support for different digest algorithms.

### PR DESCRIPTION
**Pull request by amadejkastelic**

### CODE REVIEW

**Comment by Daegalus** [comment]
This looks great, thank you. I have a busy day, so I won't be able to merge this till later tonight but I'll try to get to this quickly.

**Comment by amadejkastelic** [comment]
No problem. Take your time and enjoy the weekend!

**Comment by amadejkastelic** [comment]
Any news about merging?

**Comment by Daegalus** [comment]
I am very sorry for the delay, I honestly got sidetracked and forgot. I will do it now.

**Comment by Daegalus** [comment]
Pushed as 1.0.3

**Pull request merged**
